version: 2

models:
  - name: customers
    description: Dimension table containing customer attributes including location information.
    columns:
      - name: customer_id
        description: Primary key for the customer.
        tests:
          - not_null
          - unique

  - name: products
    description: Dimension table for product metadata including category.
    columns:
      - name: product_id
        description: Primary key for the product.
        tests:
          - not_null
          - unique
      - name: category
        description: Product category.

  - name: fct_orders
    description: Fact table with one row per order line item. Includes product, customer, quantity, and payment info.
    columns:
      - name: order_id
        description: Unique identifier of the order.
        tests:
          - not_null
      - name: customer_id
        tests:
          - not_null
          - relationships:
              to: ref('orders')
              field: customer_id
      - name: product_id
        tests:
          - not_null
          - relationships:
              to: ref('products')
              field: product_id

  - name: fct_sales
    description: Customer-level sales metrics including total spent, total orders, and order date range.
    columns:
      - name: customer_id
        tests:
          - not_null
          - unique
          - relationships:
              to: ref('customers')
              field: customer_id
      - name: total_spent
        description: Total revenue generated by the customer.

  - name: customer_summary
    description: Flattened view combining customer attributes and sales summary metrics.
    columns:
      - name: customer_id
        tests:
          - not_null
          - unique
          - relationships:
              to: ref('fct_sales')
              field: customer_id
      - name: avg_order_value
        description: Average order value for the customer.

  - name: product_performance
    description: Performance metric of each product
    columns:
      - name: category
        description: Catergory of Product

      - name: avg_sales_per_category
        description: Average sales per product category
        tests:
          - not_null
