version: 2

sources:
  - name: raw_tables
    database: ECOMMERCE
    schema: RAW
    tables:
      - name: raw_orders
      - name: raw_customers
      - name: raw_products
      - name: raw_payments
      - name: raw_orderitems